### ISSUE TITLE
About the loss curve

### ISSUE THREAD

**Issue by pilot2022** [heng-hw/SpaCap3D#1]
Hello, thanks for your work and code!

Why the loss curves of x and y are unstable while z is stable？
<img width="398" alt="0d2c596b6092d1bfc55ddb447a42399" src="https://user-images.githubusercontent.com/83114961/172099890-0bcb1e9a-2d47-46d1-a079-fda774142460.png">
Did this happen during your training?

**Comment by heng-hw** [comment]
Hello @pilot2022, 

Thanks for your interest!
The oscillation of spatiality learning along the x- and the y-axis could be caused by the occasionally occurring inconsistent language label supervision. If you look at the dataset, you would find that for some objects, the collected labels are sometimes contradicted in descriptions about "left/right" and "front/behind" (but there are no such issues for "below/above", so learning along the z-axis is stable). Hope this helps!

Best,
Heng
